# -*- coding: utf-8 -*-
"""demographic_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i23NpgCyv24kvW0Izbbjofn_ul8_iM9G
"""

!python -m pip uninstall matplotlib
!pip install matplotlib==3.1.3
!pip install momi

import momi

def model_func(params):
  N_anc, N_anc_b, N_anc_s, N_mod_b, N_mod_s, T1 = params
  model = momi.DemographicModel(N_e=1e5)
  model.add_leaf("pygmaeus", N=N_mod_b, g=np.log(N_mod_b / N_anc_b) / T1)
  model.add_leaf("abelii", N=N_mod_s, g=np.log(N_mod_s / N_anc_s) / T1)
  model.move_lineages("pygmaeus", "abelii", N=N_anc, t=T1, g=0)
  return model
